### PR TITLE
upgrade version of aws-xray-sdk-core

### PR DESCRIPTION
**Pull request by matthewbpt**
#### Is it a breaking change?:

NO

### Why did you make these changes?

So this package can be added to projects using node engine > 8

### What's changed in these changes?

Only the minimum version required of aws-xray-sdk-core

### Submission Type

* [ ] Bugfix
* [X] New Feature
* [ ] Refactor

### All Submissions

* [X] Have you added an explanation of what your changes?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you checked potential side effects that could make bad impacts to other services?

### New Features

* [ ] Have you configured CI/CD properly?
* [ ] Have you configured optimal memory size and timeouts of Lambda Function?
* [ ] Have you grant required permissions (e.g. IAM Policy, VPC Security Group)?
* [ ] Have you made required resources (e.g. DynamoDB Table, RDS Cluster)?
* [ ] Does it requires native addons dependency?

### CODE REVIEW

**Review by mooyoul — APPROVED** [review]
LGTM - Thank you!

**Comment by mooyoul** [comment]
FYI - This PR will be merged after #9 is resolved

**Comment by mooyoul** [comment]
Hello @matthewbpt, We need to resolve conflicts to merge this. Could you rebase base again? thanks

**Comment by matthewbpt** [comment]
It looks like the upstream change also upgraded the same package I wanted to upgrade, so this PR is not needed anymore. I can use this package in our project now!

**Pull request closed without merging**
